stages:
  - build
  - release

build:
  stage: build
  image: andrerichter/tum-dissertation-latex
  script:
    - make pdf-local
  after_script:
    - mkdir release
    - FILE=`date +%Y%m%d`_dissertation_${CI_COMMIT_TAG}.pdf
    - mv dissertation.pdf release/${FILE}
  artifacts:
    name: "${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${CI_COMMIT_SHA}.pdf"
    expire_in: 15 min
    paths:
      - release/*.pdf
  only:
    - tags

release:
  image: inetprocess/gitlab-release
  stage: release
  dependencies:
    - build
  script:
    - gitlab-release release/*.pdf
  only:
    - tags
